### ISSUE TITLE
builder.writeStatic is not a function

### ISSUE THREAD

**Issue by erezsh** [antony/sveltekit-adapter-browser-extension#23]
I'm getting this error in a new sveltekit project:

```
node_modules/sveltekit-adapter-browser-extension/adapter-browser-extension.mjs:93
                        builder.writeStatic(assets)
                                ^

TypeError: builder.writeStatic is not a function
    at adapt (file:///C:/code/ntr/TotalRecall/node_modules/sveltekit-adapter-browser-extension/adapter-browser-extension.mjs:93:12)
    at adapt (file:///C:/code/ntr/TotalRecall/node_modules/@sveltejs/kit/src/core/adapt/index.js:30:8)
    at finalise (file:///C:/code/ntr/TotalRecall/node_modules/@sveltejs/kit/src/exports/vite/index.js:701:13)

Node.js v18.13.0
```

**Comment by antony** [comment]
Solved by @Mlocik97
